### ISSUE TITLE
Provide an ACL File JWT backend.

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#111]
In https://github.com/iegomez/mosquitto-go-auth/pull/90, @pmous proposes a syntax to allow users map JWT claims to topic read/write/subscribe permissions.

It was suggested that the syntax may be difficult to understand and too specific to his use case. I propose the following alternative which extends the current ACL syntax used in the Mosquitto project and emulated in the Files backend of this project:

1. An addtional option `auth_opt_jwt_aclfile` in which the use could specify an extended-syntax ACL file
2. We extend the ACL file syntax to allow subsitution of jwt claims, in a similar way to the current facility to substitute `user`and `clientid`. 
Examples:

The following would allow a user with claims `"sub":"pmous"` and `"scope":"mqtt-extension"` or `filter-extension`, read access to `myndr/preferences/pmous`

```
# The first line in the next group states that the ACLs following are available to anybody whose `scope` is set to "mqtt extension", similarly to the way that a 1user` line works in the Files ACL
# The second line substitutes the `sub`claim into the path
jwtclaim.scope mqtt-extension
topic read myndr/preferences/%jwtclaim.sub%

jwtclaim.scope filter-extension
topic read myndr/preferences/%jwtclaim.sub%
```
if necessary we could extend the syntax further so that the example above becomes:
```
jwtclaim.scope mqtt-extension, filter-extension
topic read myndr/preferences/%jwtclaim.sub%
```
The following would allow any user with a claim site_id`` set to `my_wonderful_site` read access to `v/my_wonderful_site/#` and write access to   `v/my_wonderful_site/ack`
```
topic read v/%jwtclaim.site_id%/#
topic write v/%jwtclaim.site_id%/ack
````

**Comment by iegomez** [comment]
I already commented a bit on the other 2 issues for JWT, but this one deserves it's own response as I believe having a files like interface for JWT is a really good idea (sorry if my criteria looks different, I'm just going with some sort of _feel_ on how would these changes fit and work in the general picture). I'm totally on board with extending JWT to allow checking rules like static files do, not sure yet if in the exact same way or with the special suggested syntax and regexp abilities. I'll give it some more thought after I go over all the discussion in the original PR.

**Comment by pmous** [comment]
I think extending the ALC syntax is indeed a better solution. Hope it is not too much work, though.
Somre remarks:
I looked at the manpage and the syntax is a little different, 
`pattern [read|write|readwrite] <topic> where <topic> might have %u/%c`
So lets change:
• only use one %. 
• pattern instead of topic in front of it.
• lets support %c and %u for client-id resp. user id.
So:
`pattern read myndr/preferences/%jwtclaim.sub
`

Further more, jwtclaim.scope mqtt-extension is a bit odd. The first word is a keyword and I think we should keep the same naming convention, like choose "jwtclaim_scope", or "jwt_scope", or just (preferably) "scope". If it is still needed to make configurable which claim actually is the scope, we could use an option for this, like the option I had: jwt_acl_scope_field. But this option should not go in the acl-file itself, it would be a plugin-option. Not sure if this is needed anyway.

But if your intent was to make arbitrary fields part of an arbitrary check in a rule, your syntax might be interesting.  Something like:
jwtclaim.<field> <some-string>
But I don't need that, if scope would be implemented, that is. So in my opinion this would be a nice to have.

**Comment by iegomez** [comment]
Hi, @pmous and @sirockin! I'm working on the basis right now, moving files checks to their own package so they may be used from both the Files and JWT backends, but somehow I managed to screw up paths to test files. :facepalm: 
Anyway, I expect to have a files-like interface available for JWT during the next week, and I gather we could start from that. I was thinking we could define some rules mechanism that would allow to simply pass them to the backend instead of having it hardcode them, and I have a couple of ideas on how to allow that, but I'll let you know when the groundowrk is done so we can follow from there.

Cheers to you both!

**Comment by pmous** [comment]
Good work! Except for the screw up part, lol!

**Comment by iegomez** [comment]
@pmous @sirockin here's that promised PR: https://github.com/iegomez/mosquitto-go-auth/pull/166

Feel free to bash it all you want, I sent you both invites to the repo so I can request your reviews and you may chime in after accepting the invite. Of course, I reserve the right to merge anything to myself: not that I'm an asshole or believe I'm one of those benelovent dictators that are so common in software: considering the effort and the time this project takes me, I just like to be able to give a look to any contribution before it's merged. I'll let you guys tell me if that's ok or not. :shrug: 

As you may see, the added JWT checker interface goes a long way to support anything we might want to add as a JWT checking technique, and makes the upper caller very unaware of the underlying implementation. So also feel very free to open a PR with the original discussed syntax or whatever new version you have of it, I'll now gladly review and add it.

Cheers!

**Comment by iegomez** [comment]
I'm closing this issue for now, but you can let me know if you want to revisit the idea.

Cheers!
