### ISSUE TITLE
Enhancement: Optimise number of http requests by allowing http and remote jwt backends to return an ACL

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#114]
I raised this in #90 and I realise it would not be trivial to implement but thought it may be useful to flag up here as a possibile enhancement.

Currently a call is made to the http backends each time a user connects, then each time a publish/subscribe/read is carried out. In most cases, the access control rules are static for the duration of a connection so we could limit the number of http requests to one per user connection by:

1. Allowing the `getuser_uri` endpoints to return an ACL in json form
2. Making `getaclcheck_uri` optional

The effect of this would be that if `getaclcheck_uri` is not set, the plugin checks the reponse for the `getuser_uri` endpoint for an ACL in json form, and caches it. It then checks this list each time it needs to validate a publish/subscribe/write. If an ACL is not reuturned in the response, it presumes superuser access.

As @pmous pointed out, this would require caching, and so `auth_opt_cache` to be set true.

**Comment by pmous** [comment]
This would not work for a normal cache-mechanism. Caches have an expire. After that, the data would be gone and the checkACL code has no way to retrieve that info, since it is the getuser's responsibility.
What I meant was just turn on caching and be done. Once cached, repeated acl checks don't end up doing a http call, until the cache is invalid. Then the code "knows" how to retrieve fresh data.  
For your idea you'll need a state/session mechanism. GetUser will set state with acl data, checkacl will use the state. Then the responsibility is clear. One might use a db-backend for this.

I think keeping the Mosquitto code stateless is a strong argument. It is elegant, simple and reliable. If you want less http, just use a transparent cache. But this is my opinion. I just read gomez's reply in #113, and I think he agrees.

**Comment by iegomez** [comment]
Yup, definitely agree with @pmous here!
