### ISSUE TITLE
No release?

### ISSUE THREAD

**Issue by Bacto** [iegomez/mosquitto-go-auth#13]
Hi,

Thanks for this promising plugin!

Unfortunately it seems that no release have been published yet.
Is it possible to publish one to follow new versions in future please?

Thanks :)

**Comment by iegomez** [comment]
Hi! Thank you for your kind words.

I believe you only mean version releases, i.e., tag versions and release tarballs or zips with the current code, or are you looking for binary releases too? The first case seems like a good idea, I'll check the current code for any cleanup needs and make a first release today following semver probably (I'll start at 0.1.0 for now).

Let me know what you think.

**Comment by Bacto** [comment]
Sorry if I wasn't clear enough.
I meant version releases, no binary releases.

Thanks for your prompt reply and action :)

**Comment by iegomez** [comment]
Oh, no, it was clear enough, I was just wondering if binaries were requested too. I've just made a release against tag 0.1.0 available but didn't include any binaries as it's probably best to build manually against the correct version of mosquitto.

Let me know if there's anything else, or just close the issue otherwise.
Thanks for the feedback!

**Comment by Bacto** [comment]
It's perfect. Thank you :)
