### ISSUE TITLE
Segmentation fault on Alpine Linux (Musl)

### ISSUE THREAD

**Issue by Bacto** [iegomez/mosquitto-go-auth#14]
Hi,

Unfortunately the plugin doesn't work on Alpine Linux: Mosquitto crashes because of a segfault.
From GDB, I've got this trace: `#0  0x00007f3a34102660 in runtime.sysargs () from /usr/local/lib/go-auth.so`

It seems that there is a bug with GO c-shared builds and Musl.

More informations can be found on this issue:
https://github.com/golang/go/issues/13492

Unfortunately, I have no idea if the problem can be solved directly on mosquitto-go-auth code or if GO has to be patched.

**Comment by iegomez** [comment]
Hi, that's really unfortunate. Sadly, I don't run Alpine Linux nor musl as libc. I could test this in some kind of sandbox (so I don't mess up my work machine) when I get the time, but it'd probably be better and faster if you could test it with newest Go version instead of the 1.10.3 mentioned in the readme to see if it works.

If it doesn't, then I'm sorry, there's probably nothing I can do from the plugin's side as it depends on cgo and Go would need to have this fixed in a future release.

**Comment by Bacto** [comment]
I've tried with Go version 1.11.2 and unfortunately it doesn't work neither, so we are in a dead way for now, waiting for Go to resolve this issue :-/

**Comment by iegomez** [comment]
Sorry to hear that. If you could get meaningful traces with gdb and delve, it could help to reply to that issue to see if it gets some traction.

All I can recommend for now is to go with https://github.com/jpmens/mosquitto-auth-plug instead, or if you wanna have some fun maybe fork this and replace the cgo efi with some communication layer (I always wanted to see how fast gRPC could work for this, but of course any rpc, pub/sub, socket, etc. may work).

Good luck!

**Comment by Bacto** [comment]
I don't develop in Go so I can't start a such big project ;)
I finished by compiling mosquitto-go-auth with libc.

**Comment by iegomez** [comment]
Was that enough?

**Comment by Bacto** [comment]
Yes but not on Alpine Linux as we have to use Musl on it.
I've finished by using an Ubuntu (with libc)

**Comment by iegomez** [comment]
I've never used Alpine Linux so I didn't know if you could swap for another libc.
Thanks for the report and your help testing things.

I'll close it now.
