### ISSUE TITLE
mosquitto_sub not working.

### ISSUE THREAD

**Issue by thilojaeggi** [iegomez/mosquitto-go-auth#142]
Hi there.

I'm trying to sub to a topic but it doesn't work.
![image](https://user-images.githubusercontent.com/20727326/104389226-45f44580-553b-11eb-981f-eb8eb884eac6.png)
![image](https://user-images.githubusercontent.com/20727326/104389234-4b519000-553b-11eb-8a3c-f793e02bcfeb.png)
![image](https://user-images.githubusercontent.com/20727326/104389267-5b696f80-553b-11eb-9cc7-a2cea77942d1.png)
![image](https://user-images.githubusercontent.com/20727326/104389342-8227a600-553b-11eb-92f6-597ecd8cb412.png)
Does anyone know why this isn't working?

Thanks.

**Comment by manuelmaurer** [comment]
First of all, your acl table does not contain the column username, therefore the query will never work! I recommend skipping the auto_inc field in users table (because it is just not necessary, you already have a PK in your username) and then reference that in your acl table:
```
MariaDB [mqtt]> describe users;
+----------+--------------+------+-----+---------+-------+
| Field    | Type         | Null | Key | Default | Extra |
+----------+--------------+------+-----+---------+-------+
| username | varchar(20)  | NO   | PRI | NULL    |       |
| pw       | varchar(250) | NO   |     | NULL    |       |
| super    | tinyint(1)   | NO   |     | 0       |       |
+----------+--------------+------+-----+---------+-------+
3 rows in set (0.001 sec)

MariaDB [mqtt]> describe acls;
+----------+---------------------+------+-----+---------+----------------+
| Field    | Type                | Null | Key | Default | Extra          |
+----------+---------------------+------+-----+---------+----------------+
| id       | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| username | varchar(20)         | NO   | MUL | NULL    |                |
| topic    | varchar(255)        | NO   |     | NULL    |                |
| rw       | int(11)             | NO   |     | NULL    |                |
+----------+---------------------+------+-----+---------+----------------+
4 rows in set (0.002 sec)

MariaDB [mqtt]>
```

Additionally there seems to be a problem with subscribe that looks somewhat like the problem in #118

As a quick fix, I've updated my users to a permission level of 4. This will allow subscribing to topics. Also not sure, but you might need to update your acl query for writes to actually work (not tested though):

```
auth_opt_mysql_aclquery SELECT topic FROM acls WHERE (username = ?) AND (rw >= ?)
```

**Comment by thilojaeggi** [comment]
This is how it looks now.
![image](https://user-images.githubusercontent.com/20727326/104498821-7e982b80-55dc-11eb-8576-55589c9d8242.png)
And this is my config:
![image](https://user-images.githubusercontent.com/20727326/104498879-8eb00b00-55dc-11eb-8ecf-ab26a94190d0.png)
Sadly, mosquitto_sub still doesn't work.
Thank you for your help btw.

**Comment by kaluginvlad** [comment]
The simplest solution - try HTTP backend and request data from external CGI app... I think, that it better for integration with the IOT project.

**Comment by manuelmaurer** [comment]
@kaluginvlad HTTP is fine if you are using a different authentication database anyways. Just adding a webserver in front of it to get rid of problems is not a solution, especially as you might put quite some load on the webserver (if you are not using a cache), depending on the usage model.

@thilojaeggi config looks fine so far. Please enable logging for the plugin and check what the log says:
```
auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/auth.log
```
it will at least tell you, if the problem is with authentication or with the acls

**Comment by kaluginvlad** [comment]
@manuelmaurer I have integrated Mosquitto with my existing IOT project. And HTTP backend is what I was looking for. And of course I have configured caching :)

**Comment by thilojaeggi** [comment]
Got it to work. My error was in my mysql query.
Table is called acl not acls.
