### ISSUE TITLE
GDPR and need for no special database user

### ISSUE THREAD

**Issue by jhelberg** [iegomez/mosquitto-go-auth#149]
All my database software tries to avoid any sort of superuser, hence end-users always connect to the database themselves. For mosquitto and your auth-plugin, I want to do the same thing. It works nicely, but I'm interested in whether you are willing to discuss making pg_user and pg_password non-mandatory and use the given user-credentials as database login-credentials.

I'm happy to participate in the development of mosquitto-go-auth also of course, also for stuff not concerning GDPR and postgres.

**Comment by iegomez** [comment]
Hi, @jhelberg!

I'm not so sure about the option since it'd mean opening a new DB client for each user check, keeping it open for some time (how much?) for subsequent superuser and ACL checks, closing it (when?), etc. So basically, instead of having a plugin's client which provides a pool of connections to use, we'd have to handle a pool of clients per user, which is absolutely non trivial.

That said, if you want to work on it and come up with a nice solution, I'll gladly review any contributions.

Cheers!
