### ISSUE TITLE
tag latest docker image

### ISSUE THREAD

**Issue by YerayAlonso** [iegomez/mosquitto-go-auth#158]
I found the latest image at [docker hub](https://hub.docker.com/r/iegomez/mosquitto-go-auth/tags?page=1&ordering=last_updated) is tagged just as "latest" so (AFAIK) there's no way to use reference it in a docker compose and avoid upgrading to a newer version when you'll push it.

If I'm not wrong, tagging that image (ie 1.4.2) would allow us to force that version to be used even if you push a new image.

**Comment by iegomez** [comment]
Hi, @YerayAlonso! Docker images are automatically built for each release as well as for current master. You may use tagged releases instead of latest if you wish so.

**Comment by iegomez** [comment]
Does that make sense or am I missing something?

**Comment by YerayAlonso** [comment]
> as well as for current master

Ah, this explains it.  
Then I guess you could set a `beta-x` tag or similar to images build using master so we can fix it in our docker-compose.

Or I can just be tuned and check the latest release when you'll push it.

Thanks for the project!

**Comment by iegomez** [comment]
To be honest, Docker is not my cup of tea and I don't know what are the best practices. It was a contributor that helped me set automated build in Dockerhub a looong time ago. 

My 2 cents is that having `latest` track changes in `master` makes sense since those are effectively latest changes, while pinning the version is always possible since releases are also auto built and tagged with the release number. But again, I'm not a Docker fan and could be wrong. 🤷‍♀️

**Comment by iegomez** [comment]
@YerayAlonso any feedback on that? Again, I may be very wrong about my take on docker builds since I don't really use them.

**Comment by YerayAlonso** [comment]
Sorry for not replying your last comment.  
If I understand it correctly, we can say the build process has two steps:
- Set a new `number` to the "previous" `latest` image.
- Build a new image with `master` and set the `latest` tag to it.

The idea would be to just set two labels to the image built with `master`: `latest` and `number`.

I can take a look at the code doing the automated build if you point me to where it is.

**Comment by iegomez** [comment]
Ah, well, that's the thing: there's no code nor build process done in the repo, it's Docker Hub automated build that's doing the job:
![image](https://user-images.githubusercontent.com/5600043/111918822-b355b280-8a65-11eb-9fe0-b4cad6677740.png)

I have no idea really, but I don't think it allows to tag the previously built image with some increasing number before building the new `latest`. So in order to do achieve your goal, we'd have to run our own building system.

**Comment by iegomez** [comment]
They also don't seem to support e.g. tagging the build against the commit hash, it'd have to be done manually: https://forums.docker.com/t/reference-git-commit-hash-in-the-docker-hub-automated-build-docker-tag-field/98487

**Comment by YerayAlonso** [comment]
I'm afraid there are things that scape my knowledge here. There seems to be the possibility to [tag the docker images with the github tags](https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds), but I'm not sure if this is compatible with building a `latest` image with the `master` branch as you are doing.

No problem for me. You can close this.

**Comment by iegomez** [comment]
I'll look at that to see if it may be done, thanks for the link!

**Comment by thomastvedt** [comment]
One alternative could be to move docker build and publish to Github actions? You can still publish docker image to dockerhub, but let Github action do the build, generate tags, etc.

**Comment by iegomez** [comment]
That sounds like a good idea, just not one I want to prioritize. But a PR with the base work would be very much appreciated, I can later fill in the blanks with needed secrets and configuration values.

**Comment by iegomez** [comment]
Docker images are now being built through Github actions, so I'm closing this issue. Let me know if thereś any other concern, @thomastvedt.

Cheers!
