### ISSUE TITLE
wss / websockets over ssl

### ISSUE THREAD

**Issue by alljoynsville** [iegomez/mosquitto-go-auth#185]
I can't connect to wss (websockets over ssl). It worked in older 1.5/1.6 versions. 
Is there a different way to use it now?

**Comment by iegomez** [comment]
Hi, @alljoynsville. Could you be a bit more specific about what connection would be that? If you're talking of client to Mosquitto broker connection, then that has nothing to do with the plugin but with Mosquitto itself. Or are you referring to something else?

**Comment by alljoynsville** [comment]
Hi, 
I'm using a javascript mqtt client - websockets over tls
with image iegomez/mosquitto-go-auth:1.6.1-mosquitto_1.6.14 it works as expected
with image iegomez/mosquitto-go-auth:1.7.0-mosquitto_2.0.9 connection fails

**Comment by iegomez** [comment]
Ah, you meant using docker images, that's important because indeed they provide an already built `mosquito`.

That said, this is the commit for `1.7.0` changes, there's nothing related to how the image is built there: https://github.com/iegomez/mosquitto-go-auth/commit/5dc063f1041b94dd67ededf47f79fa58b0968c68

So I'd really need more details, logs, etc., to even start looking. Could you try building the image yourself instead of fetching it from Dockerhub, and maybe try with different Mosquitto versions to see if there's some specific one that fails?

**Comment by iegomez** [comment]
One more thing, are you able to connect through regular, non TLS websockets? That would help determining if its TLS support or websockets themselves that are failing. Since you're using Mosquitto `2.0.9` in version `1.7.0`, maybe that version has some issues with the libwebsockets one.

**Comment by alljoynsville** [comment]
I'm not using non secure sockets but ill try it and update you.
I'll also try to build locally and test with the local build

**Comment by alljoynsville** [comment]
ok, I verified, websockets works, both in secure and unsecure mode. thanks for your help and time!

**Comment by iegomez** [comment]
@alljoynsville I'm glad it's working for you now.

Cheers!
