### ISSUE TITLE
mosquitto.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by BrentLeemans** [iegomez/mosquitto-go-auth#205]
##question 1##
I've copied the service config from the README and when I try to run the mosquitto service: `sudo systemctl start mosquitto` I get the following errors: 
```
systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 5.
systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
systemd[1]: mosquitto.service: Start request repeated too quickly.
systemd[1]: mosquitto.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.
```

However I can run mosquitto this way: `mosquitto -v -c mosquitto.conf`

##question 2##
My current userquery looks like this:
`auth_opt_mysql_userquery SELECT password FROM user WHERE name = ? limit 1`

This is the config of my hashing algorithm:
```
auth_opt_hasher pbkdf2
auth_opt_hasher_salt_size 16
auth_opt_hasher_iterations 1000
auth_opt_hasher_keylen 64
auth_opt_hasher_algorithm sha512
auth_opt_hasher_salt_encoding base64
```
This would work if I used bcrypt as the hashing algorithm, but pbkdf2 requires a salt. How would I write my userquery to pass in the salt?

Any idea on how I could fix these problems?

**Comment by iegomez** [comment]
1) I don't know what you system is and why it fails to start the service, you'll have to do some more debugging. Sadly, I can't keep guides for all systems nor is _how to run Mosquitto_ in the scope of this project; hell, I can't even keep the simple examples up to date because I don't use Mosquitto nor the plugin at the moment. 😅 

2) You don't need to pass anything, the `salt` is stored along with the hash, so when the plugin gets the `username/password` combo, it'll look up the user and select the column you passed in your query, which should correspond to the password hash, and then using the given hashing parameters and the stored salt it'll hash the `password` it received for check, hash it and compare it to the stored one.

**Comment by BrentLeemans** [comment]
1. I run Ubuntu and when I disable the plugin my service runs. I will do some more debugging and try to find the problem.
2. In my database I have stored the salt as a separate property, this is what the table looks like: `name`, `password`, `salt`.  I've had some problems with the pbkdf2 hasher but I will try again tomorrow and see what comes up. Bcrypt works tho so I might just use that one. Thanks for the quick reply!

**Comment by iegomez** [comment]
@BrentLeemans there's no way to pass that separate salt you have in your DB, PBKDF2 generates a random salt when hashing and stores it along with the hash, so that's what gets used to hash the incoming password before comparison.

**Comment by BrentLeemans** [comment]
All clear, thanks!
