### ISSUE TITLE
Enhancement: Provide all JWT claims for backend

### ISSUE THREAD

**Issue by ray66rus** [iegomez/mosquitto-go-auth#229]
Why not send to `js`-type JWT backends all the claims, not just user name? It is not possible (or may be I just haven't found a way?) to use a third-party library in the JS script to parse JWT token string. In the same time if we need only the data from the JWT token to decide if we should allow user to access the topic, using a `remote`-type backend with the separate server seems to be an overkill. Providing the parsed data by the plugin itself looks like a reasonable solution.

**Comment by iegomez** [comment]
@ray66rus yeah, I think adding an option to pass all claims may be reasonable. I'll try to implement it soon.

Cheers!

**Comment by ray66rus** [comment]
Cool. I think I can make a Pull Request concerning this feature

**Comment by iegomez** [comment]
That'd be great, thanks!

**Comment by ray66rus** [comment]
NP, but I need a piece of advise. You now use custom `Claims` struct with embedded `StandardClaims`. But if we are passing all the claims to the script this approach doesn't work (or I just don't know how to do it :-)). I'd like to change struct-style parsing to using `MapClaims`, but first I want to ask if you think this is ok. Maybe there is a better way, without changing the already-existing code?

**Comment by iegomez** [comment]
Sorry, I missed your comment. The current claims are like that because this project was tightly related to ChirpStack for a long time, and they used custom `username` claim instead of the standard `subject` one. I can definitely see a way of switching to map claims and keep supporting that as well as allowing for other user defined claims, though that could be achieved by constructing the claims struct on the fly on initialization.

What I'm curious about is the claim (hehe) that keeping the wrapped standard claims wouldn't work. Why is that? I think we can easily serialize and pass them along, but maybe I haven't given it too much though.

**Comment by ray66rus** [comment]
Well, I'm not a real Golang jedi (actually, I've never written anything in Go before :-D), so maybe I just missed some language feature - I have no idea how to create a structure combining fixed (standard claims) and arbitrary (user-defined claims) fields on the fly. Anyway, I've created a Pull Request and humbly waiting for your review :)
