### ISSUE TITLE
Redis backend query options

### ISSUE THREAD

**Issue by Ciruxx** [iegomez/mosquitto-go-auth#38]
Hi, thanks for your work!
I would ask about `auth_opt_redis_userquery` and` auth_opt_redis_aclquery`, why were these options removed?

Is there any way to customize the queries?

Thanks!

**Comment by iegomez** [comment]
Sorry, I hadn't seen the issue before.

> I would ask about auth_opt_redis_userquery and auth_opt_redis_aclquery, why were these options removed?

What do you mean with removed? Those never existed as such. The correct way to define Redis rules (which include `user`, `superuser` and `acl` permissions) is covered here: https://github.com/iegomez/mosquitto-go-auth#redis.

> Is there any way to customize the queries?

Not as a configuration option, so you'd have to modify the source code and then rebuild the plugin.

**Comment by Ciruxx** [comment]
Sorry, I read this:

> It is greatly inspired in jpmens' mosquitto-auth-plug.

and thought it was compatible with `mosquitto-auth-plug`.

Are you going to implement this feature?

Thank you!

**Comment by iegomez** [comment]
Sorry, no, they are not compatible in that sense, Redis backends work differently in each plugin. 

I'm not sure about adding support for `auth_opt_redis_userquery` and `auth_opt_redis_aclquery` (as in `jpmen's` plugin) because those only allow to query for an existing user and match against exact topics for ACLs, providing no way to check for user password, allow superusers or to control read/write/subscribe permissions for topics. That's the reason I went with a different approach: to support all those options.

So though I'm not discarding it completely as being compatible is a desirable goal, it's not a priority or even a promise for the future.

**Comment by iegomez** [comment]
I'm sorry but I don't think I'll add support for this, but I'm open for a contribution that adds it **and** keeps the current functionality. Let me know if you'd be interested in doing such work. In the meantime, I'll close this issue.
