### ISSUE TITLE
MySQL Read Only Not Working.

### ISSUE THREAD

**Issue by shaneyake** [iegomez/mosquitto-go-auth#46]
Hi,

I can get MySQL to have write only with an 'rw' value of 2 and read-write with 'rw' value of 3 but if I set it to 1. It doesn't work. 

I tried writing my own query to save the '?' inputs and got $username on the first ? as expect and 2 for write and 4 for read on the second '?'

Does anyone know what is wrong? Thanks

**Comment by gbcat** [comment]
Facing the same problem. I am using PostgreSQL.

**Comment by iegomez** [comment]
Take a look at prior issues for more details (e.g.. https://github.com/iegomez/mosquitto-go-auth/issues/18), but in short it has to do with Mosquitto 1.5.x and later having another option, MOSQ_ACL_SUBSCRIBE, associated to 4. So if your clients are trying to subscribe to the topics before or instead of reading it and they don't have permissions for that, they'll be rejected.

The solution for this is to either grant subscribe permissions on your tables by adding 4 to the access permissions, to handle it in your query or a mix of both.

**Comment by iegomez** [comment]
@shaneyake, were you able to make it work?

**Comment by shaneyake** [comment]
I have not been able to make it work.
Do you have an example SQL query?

Thanks

**Comment by iegomez** [comment]
It depends on what your data looks like, but let's say your table has columns [username, topic, acc], and that you have a query like `SELECT topic FROM acl WHERE (username = $1) AND rw = $2`, then to enable that user to receive messages on a topic you'd need to have rows: 
```
username | topic | acc
  user     topic    1
  user     topic    4
```
This means that the user is able to subscribe and read.

Now, depending on your requirements, this could be treated differently. For example, with this query you'll be giving access whenever the `acc` matches that of a record or if it's 4: `SELECT topic FROM acl WHERE (username = $1) AND (rw = $2 OR $2 = 4)`. That means that any request to **subscribe** to a topic, i.e. request `acc` 4, will be successful given that there's a record that includes both the username and the topic, without minding what `acc` is in that record, because you explicitly said in your query you needed them to either match or be 4.

**Comment by shaneyake** [comment]
Okay cool, that works. Thanks for all the help!
