### ISSUE TITLE
Possible to use with docker?

### ISSUE THREAD

**Issue by gusseleet** [iegomez/mosquitto-go-auth#5]
Hi!

I'm trying to setup this with docker. This is my current config-file:
```

FROM debian:jessie


# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.docker.dockerfile="/Dockerfile" \
    org.label-schema.license="BSD 3-Clause" \
    org.label-schema.name="docker-mosquitto" \
    org.label-schema.url="https://hub.docker.com/r/toke/mosquitto/" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-type="Git" \
    org.label-schema.vcs-url="https://github.com/toke/docker-mosquitto"

RUN apt-get update && apt-get install -y wget && \
    wget -q -O - https://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | gpg --import && \
    gpg -a --export 8277CCB49EC5B595F2D2C71361611AE430993623 | apt-key add - && \
    wget -q -O /etc/apt/sources.list.d/mosquitto-jessie.list https://repo.mosquitto.org/debian/mosquitto-jessie.list && \
    apt-get update && apt-get install -y mosquitto mosquitto-clients && \
    adduser --system --disabled-password --disabled-login mosquitto


RUN \
  wget https://dl.google.com/go/go1.9.5.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go1.9.5.linux-amd64.tar.gz

ENV PATH $PATH:/usr/local/go/bin
ENV GOPATH /go

RUN mkdir /go

RUN apt-get install -y git && \
  apt-get install -y make && \
  apt-get install gcc -y

RUN mkdir -p $GOPATH/src/github.com/iegomez && \
  cd $GOPATH/src/github.com/iegomez/ && \
  git clone https://github.com/iegomez/mosquitto-go-auth.git && \
  cd mosquitto-go-auth && \
  make requirements && \
  make


RUN mkdir -p /mqtt/config /mqtt/data /mqtt/log
COPY config /mqtt/config
RUN chown -R mosquitto:mosquitto /mqtt
VOLUME ["/mqtt/config", "/mqtt/data", "/mqtt/log"]


EXPOSE 1883 9001

ADD docker-entrypoint.sh /usr/bin/

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/usr/sbin/mosquitto", "-c", "/mqtt/config/mosquitto.conf"]
```
When I try to build this I get this error:
```

Installing development tools
go build -buildmode=c-archive go-auth.go
go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
auth-plugin.c:6:23: fatal error: mosquitto.h: No such file or directory
 #include <mosquitto.h>
                       ^
compilation terminated.
```

Is there any other way you could use this plugin with docker?

**Comment by iegomez** [comment]
Hi! I have little experience with docker, but this is not a docker issue. You get this error because the Go compiler can't find mosquitto's headers:

`auth-plugin.c:6:23: fatal error: mosquitto.h: No such file or directory`

You either need to install mosquitto-dev or build mosquitto from source in your image to have the headers available for the plugin, which doesn't happen when you only run this for mosquitto:

`apt-get update && apt-get install -y mosquitto mosquitto-clients`

**Comment by gusseleet** [comment]
Hi!

I changed the line to   `apt-get update && apt-get install -y mosquitto-dev mosquitto mosquitto-clients` but the Go compiler still can't find mosquitto.h. Must be something with docker then.

**Comment by iegomez** [comment]
Mmm..., it sounds as the headers aren't placed where the plugin can see them when mosquitto-dev is installed, e.g., /usr/include/mosquitto.h. You could try to see where the files are located (mosquitto.h and mosquitto_plugin.h) and make a symlink to them.

Anyway, I'd recommend that you build mosquitto manually in your docker image instead of installing from packages to have better control (for example, enable websockets or something like that). Also, mosquitto versions always seem to be pretty outdated on the official packages.

**Comment by gusseleet** [comment]
I solved it when it was build from source.

**Comment by gaetancollaud** [comment]
Installing `libmosquitto-dev` also work:
```
RUN apt-get update && apt-get install -y  libmosquitto-dev
```
