### ISSUE TITLE
Superuser request for normal user

### ISSUE THREAD

**Issue by peter3099** [iegomez/mosquitto-go-auth#59]
Hello

Thank you very much for making mosquitto go auth, I'm using the Remote JWT and everything works fine for all those request that have JWT, speccially the ones from the frontend. My problem comes for a couple of devices that connect to the same broker but they use normla user and password, they are able to connect without a problem, but the broker keep sending req to the backend to check if this users are superusers, is there any way to avoid this? So if a user is on passwords file to not be checked against superuser uri. 

there is no easy way for me to check if static user is valid or not from the backend. 

Could you please advice?

One solution will be to give this devices a JWT as well but since they are in remote locations I don't want to be changing them all the time, and if I make them last for years they will be basically a user with no password!

Thanks 
Have a nice weekend
Pedro

**Comment by iegomez** [comment]
Hi, Pedro, thanks for the kinds words!
My first idea would be to add something like a `disable_superuser` option per backend, so that way you can disable `superuser` checks and only do regular user authentication and ACLs authorization on any given backend. Would that suffice for your use case?

**Comment by peter3099** [comment]
thanks for the quick answer, 

Is nice to have the superuser feature, the problem now is that the backend files doesn't have a way to authenticate it.

Basically we need a way to disable superuser for the backend Files, or a way to authenticate it within the file. because ACL an normal user is not a problem but when it comes to check if the "file user" is superuser it eventually goes to another backend option, in mi case JWT.

Also just to let you know as well that I never managed to make the backend JWT remote work with the jwt_params_mode as JSON, I don't know why but I couldn't get the JSON decoded on the backend. If you have any example of how to decode that JSON that would be great.

**Comment by iegomez** [comment]
I'm super busy this week so probably won't have time to check it, but I'll take a look next week.

**Comment by peter3099** [comment]
Sounds like a plan! Good luck with work!

**Comment by peter3099** [comment]
Hi iegomez, just a friendly reminder about this issue! Thanks in advance!

**Comment by iegomez** [comment]
Hey, @peter3099, sorry about that. I've been a bit busy, but this is definitely in my todo list as soon as I get the time.

**Comment by iegomez** [comment]
I'm working on this right now and got a bit curious: do you have control over your users `usernames`? If that's the case you may set which backend is used to check against a request by using [prefixes](https://github.com/iegomez/mosquitto-go-auth#prefixes).

In any case, disabling superusers for given backends is a nice feature to have, but if you want to be able to have some users to actually be superusers and others not based on the backend, then it won't be enough for your use case and you'll still need to be able to tell them apart. If instead you only care about checking users and don't want anyone to be a superuser, then this will suffice.

As for the JWT errors, could you provide any more details?

**Comment by iegomez** [comment]
Here's a PR for the WIP: https://github.com/iegomez/mosquitto-go-auth/pull/63

**Comment by iegomez** [comment]
@peter3099 I just finished the PR. Besides adding the option to disable superusers per backend or globally, it also fixes an unhandled error and now correctly sets the `Authorization` header for JWT as `Bearer <token>` instead of just passing the token, which maybe solves your JWT issues.

Please review it and let me know if you see any errors so I can fix them, or confirm it looks good and I'll merge it afterwards.

**Comment by peter3099** [comment]
Thank you so much for this, let me check it and I'll come back to you! I'll look into prefixes as well, I do have control over the usernames so I can implement that together with having the chance to disable superuser

**Comment by peter3099** [comment]
Hey @iegomez , works really well

The only odd thing I see in the logs is 


`2020-05-14T10:28:45.694374697Z time="2020-05-14T10:28:45Z" level=debug msg="checking user eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTeW1waG9ueUNsb3VkIiwic3ViIjoiNFVYczU0dEpwU0VCSkx2TUpEd2ZBYiIsImVtYWlsIjoicGVkcm8uY2hpY2FsYUBhc2NvdWdoLmllIiwiaXNTeW1waG9ueSI6dHJ1ZSwiaWF0IjoxNTg5NDUwNjkMTQ2OTJ9.xjjGCiyHfjrgRPaGtFQfz5a3uxdNJFkqrK5Hwz1OIGM with backend Files",
2020-05-14T10:28:45.694377935Z time="2020-05-14T10:28:45Z" level=debug msg="checking user eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTeW1waG9ueUNsb3VkIiwic3ViIjoiNFVYczU0dEpwU0VCSkx2TUpEd2ZBYiIsImVtYWlsIjoicGVkcm8uY2hpY2FsYUBhc2NvdWdoLmllIiwiaXNTeW1waG9ueSI6dHJ1ZSwiaWF0IjoxNTg5NDUwNjkyLCJleHAMTQ2OTJ9.xjjGCiyHfjrgRPaGtFQfz5a3uxdNJFkqrK5Hwz1OIGM with backend JWT",
2020-05-14T10:28:45.831864850Z time="2020-05-14T10:28:45Z" level=debug msg="jwt request approved for eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTeW1waG9ueUNsb3VkIiwic3ViIjoiNFVYczU0dEpwU0VCSkx2TUpEd2ZBYiIsImVtYWlsIjoicGVkcm8uY2hpY2FsYUBhc2NvdWdoLmllIiwiaXNTeW1waG9ueSI6dHJ1ZSwiaWF0IjoxNTg5NDUwNjkyLCJleHTQ2OTJ9.xjjGCiyHfjrgRPaGtFQfz5a3uxdNJFkqrK5Hwz1OIGM",
2020-05-14T10:28:45.831893699Z time="2020-05-14T10:28:45Z" level=debug msg="user eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTeW1waG9ueUNsb3VkIiwic3ViIjoiNFVYczU0dEpwU0VCSkx2TUpEd2ZBYiIsImVtYWlsIjoicGVkcm8uY2hpY2FsYUBhc2NvdWdoLmllIiwiaXNTeW1waG9ueSI6dHJ1ZSwiaWF0IjoxNTg5NDUwNjkyQ2OTJ9.xjjGCiyHfjrgRPaGtFQfz5a3uxdNJFkqrK5Hwz1OIGM authenticated with backend JWT",
2020-05-14T10:28:46.054830707Z time="2020-05-14T10:28:46Z" level=debug msg="user eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTeW1waG9ueUNsb3VkIiwic3ViIjoiNFVYczU0dEpwU0VCSkx2TUpEd2ZBYiIsImVtYWlsIjoicGVkcm8uY2hpY2FsYUBhc2NvdWdoLmllIiwiaXNTeW1waG9ueSI6dHJ1ZSwiaWF0IjoxNTg5NDyLCJleHATQ2OTJ9.xjjGCiyHfjrgRPaGtFQfz5a3uxdNJFkqrK5Hwz1OIGM acl authenticated with backend Files"`

It looks like is checking the user with the backend JWT but the ACL with the backend Files

my go-auth.conf is 
`allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_check_prefix false

# auth_opt_log_level warn
auth_opt_log_level debug
# auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log

auth_opt_backends files, jwt

auth_opt_password_path /etc/mosquitto/auth/passwords
#auth_opt_acl_path /etc/mosquitto/mosquitto-go-auth/acls

#Dev
auth_opt_jwt_remote true
auth_opt_jwt_host server_name
auth_opt_jwt_with_tls true
auth_opt_jwt_port 443
auth_opt_jwt_getuser_uri /stg/jwt
auth_opt_jwt_aclcheck_uri /stg/jwt/acl
auth_opt_jwt_params_mode form`

I don't really need the ACL right now, so not a concern, but I have the aclpath line commented so I don't know why is doing that.

also with the prefix stuff that you mentioned,  if I want a prefix for Files(for example "se") and the rest will be checked against JWT shall I put

auth_opt_backends files, jwt
auth_opt_prefixes se,
?
and the users be called "se_username" ?

Thanks again

**Comment by iegomez** [comment]
Files authorizing the JWT token user happens because if there are no ACLs for files then all checks pass:
```
//If there are no acls, all access is allowed.
	if !o.CheckAcls {
		return true
	}
```
That makes sense when you have Files as a standalone backend and all you're doing is authentication, not authorization. That is, if you're a valid user and your password checks, you may pub/sub to anything if no ACLs are in place.

Of course, that doesn't play well with other backends, so thanks for catching that! I'll try to add a fix for that in the same PR tonight.

As for the prefixes, you're right, but again that'll fail because of the above issue: `se_users` will only be checked against Files backend, but JWT users will pass ACLs freely because Files authorizes them. And since JWT tokens shouldn't be prepended with a prefix as that would result in an invalid token (this could be worked around by asking clients to prefix the tokens and then stripping them in the plugin for validation, but it needs some thought), Files need to be fixed first.
Let me think a bit about this and I'll get back to you.

**Comment by iegomez** [comment]
For now I think a reasonable way of dealing with this is:

1. For the `Files` backend, if there are no ACLs **always** grant access **when running solo**, and **never** grant access **when running along other backends**.

2. For `JWT`, if prefixes are being used, try to strip the prefix from the token: 
- If the client added the prefix and that's why the backend is being used, then the token will be valid after stripping it. 
- If they just passed the token, then trying to remove the prefix will leave the token as is and still be valid when it's checked by this backend (after potentially being checked by others first).

How does that sound?

**Comment by iegomez** [comment]
I still need to write some tests to ensure it works as intended (and document it in the readme), but I just pushed changes with said behaviour.

**Comment by peter3099** [comment]
HI iegomez, sounds great, so basically the frontend will put the prefix, then the plugin will take out the prefix so the backend can authenticate it. Sounds really good to me. 

Thanks for all the work! Have a nice weekend!

**Comment by peter3099** [comment]
Hi iegomez

**Comment by peter3099** [comment]
Hi iegomez 

Sorry for reopening this, so far the superuser disable has been working perfectly, but I'm having issues with the ACL check, it's happening all the time on the backend, and my file is basically any user can access anything because I have different brokers. If I erase the ACL file since I'm running files and jwt would that deny access to all of them? any chance to bypass that or disable ACL check?

Thanks

**Comment by iegomez** [comment]
Hey, @peter3099, sorry for the late response. Sadly, no, it's not possible to bypass it right now since that's the exact behavior we prevented:
```
	//If there are no acls and Files is the only backend, all access is allowed.
	//If there are other backends, then we can't blindly grant access.
	if !o.CheckAcls {
		return o.filesOnly
	}
```
The problem lies in tying the existence of an all path to the decision to check them, which is not ideal as it prevents your use case:
```
	if aclPath, ok := authOpts["acl_path"]; ok {
		files.AclPath = aclPath
		files.CheckAcls = true
	} else {
		files.CheckAcls = false
		log.Info("Acls won't be checked")
	}
```
So for this to work a new option, e.g. `auth_opt_files_disable_acl` would be needed. I'll consider adding it at some point.

**Comment by iegomez** [comment]
@peter3099 Could you remind me the desired output here? That is, what's your configuration, what's the exact issue and what would you desire to happen instead? I was looking to implement this but wanna double check before doing anything.

**Comment by peter3099** [comment]
Hi iegomez 

The idea was to be able to disable ACLs or to have a way to bypass them. For me is enough to authorize the user to use MQTT and basically all the user on that broker have # for read and write, so the ACL request to the backend is always 200 if the user exist. In the future I would like to implement more ACLs but I just wanted to know  if there was a way to disable it so fewer request go to the ACL backend check.

let me know if I didn't explain myself correctly. Thanks in advance

**Comment by iegomez** [comment]
Gotcha, @peter3099! Just wanted to make sure the idea was to grant access by default when disabling checks option is set, without needing to check if Files is the only backend. I'll get on it during the week.

**Comment by iegomez** [comment]
@peter3099 I'm working on this feature right now, but it turned out not to be so easy. It's fairly easy to disable `superuser` checks, even on a per backend basis, since you can always return `false` by default and wait till some backend returns `true`.

For ACLs, not so much. It's trivial to add a global `skip_acls` option, but it gets tricky when accounting for individual backends: any skipping (for ACLs) needs to know that it's effectively checking against a user that's prefixed to that backend; otherwise, it shouldn't assume anything or it'd be blindly authorizing any ACL check since a single granting response is sufficient to say the check is OK.

It's not so difficult to implement, it's just a bit ugly considering how things are structured right now, e.g. backends know nothing about prefixes. So besides the last 20 or so days that I've been too busy to do any work regarding this project, I think it's gonna take me at least another afternoon to properly refactor backends to cleanly check prefixes and nail a solution.

**Comment by peter3099** [comment]
Hi @iegomez no problem at all, I know is the end of the year and we are all busy with different things plus this year has been special... So far what you have done with this plugin is amazing so I can only say thank you. Whenever you have some time for this great, it is working so is not critical. Thanks in advance! All the best

**Comment by iegomez** [comment]
Hey, @peter3099, it's surely been a while!
A couple of days ago I wanted to resume work on this issue but didn't find the branch on my personal machine, maybe for once I used the work one to start implementation and never pushed it upstream. :woman_shrugging: 
In any case, is this still something that's needed or did you eventually add ACLs or found another way to bypass them? The more I read the issue, the more it seems strange to me.

Anyway, let me know if I should give it another go any time soon.

Cheers!

**Comment by peter3099** [comment]
Hey @iegomez no worries, it is working fine, we are still getting all the ACL requests, which is not an issue but since all my users have # for read and write topics, then it makes no sense. 

Maybe in the future we implement ACL through the backend but what I was thinking was to disable them so the only thing mosquitto go auth check is user and then superuser and ACL are granted with that.  It will be helpful in a way that clean the amount of request, see below
![image](https://user-images.githubusercontent.com/22412633/109947465-3ee2eb80-7cd1-11eb-9e63-f58eb48482b6.png)

Are those ACL request suppose to be so often?

Thanks in advance

**Comment by iegomez** [comment]
@peter3099 Well, you'd get a request on every publication and another for every consumer of the message, so I'd say yes, it's common to have a lot of them. You'll also get ACL requests when clients first subscribe to topics.

I was thinking that you could bypass all these checks by adding `Files` backend before `JWT` one, with a dummy empty file for `passwords` and a general ACL rule in `acls` one, i.e.:
```
topic #
``` 

That way, if you define `files` before `jwt` in your options, ACLs would be checked against the `Files` backend and grant general access to everything, preventing calls to your JWT service. The downside is that you'll get `user` checks against that backend before calling the JWT service, but those should be cheap since there are no `Files` users so it's an empty map read.

What do you think? Give it a try and let me know how that works for you.

**Comment by iegomez** [comment]
Another thing I'm thinking of is adding the ability to register checks for each backend, e.g.:
```
auth_opts_jwt_register user, acl
auth_opts_pg_register user, superuser, acl
...
```
This way you can simply skip backends that don't register a check when performing it. Of course, we'd need to ensure at least one backend registers each check, except maybe for `superusers`.

Anyway, food for thought.

**Comment by peter3099** [comment]
Man I'll give that a try, thanks for that, your last idea sounds really good, it will give a lot of flexibility

**Comment by iegomez** [comment]
Well, @peter3099, here's a PoC for that idea: https://github.com/iegomez/mosquitto-go-auth/pull/159

**Comment by peter3099** [comment]
Hi @iegomez, thanks for this. So now basically I can check ACLs with Files and users with JWT, right? So at the moment, I have some  users on my ACL for the Files backend check 

`user user1
topic read #
topic write #`

do I need to add a 

`topic #`

at the end with no user details correct? Because for the JWT check the username is the JWT itself am I right?

Thanks

**Comment by iegomez** [comment]
Yes, adding a general rule will make it available for all users.

I need to address a couple of comments on the PR, but it should go in this week.

**Comment by iegomez** [comment]
@peter3099 Merged and released: https://github.com/iegomez/mosquitto-go-auth/releases/tag/1.5.0

**Comment by peter3099** [comment]
HI @iegomez  thanks for this, I will try it an come back to you
Have a good weekend

**Comment by peter3099** [comment]
@iegomez works really well, thanks for doing that!
