### ISSUE TITLE
Cache in redis cluster

### ISSUE THREAD

**Issue by rechandler12** [iegomez/mosquitto-go-auth#60]
Hi!
I've made k8s deployment of mosquitto with auth plugin and redis cache. I'm using redis-cluster from bitnami: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster

And I've got following error:
```
1588272769: New connection from 10.244.0.130 on port 1883.
1588272769: Socket error on client <unknown>, disconnecting.
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 2996 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 15623 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 11261 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 14839 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 4048 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 795 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 11246 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 376 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 4978 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 2224 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 15146 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 3029 10.244.0.129:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 11178 10.244.0.205:6379"
time="2020-04-30T18:52:49Z" level=error msg="set acl cache: MOVED 2421 10.244.0.129:6379"
```

After search in the internet I have found this:
https://serverfault.com/questions/812156/redis-cluster-error-moved

So could you add support for redis cluster configuration?

**Comment by iegomez** [comment]
Hey, thanks for reporting this. I'll take a look next week.

**Comment by coldfire84** [comment]
Looks like this will need a config flag to instruct the plugin to either setup a redis client or cluster client via go-redis: https://godoc.org/github.com/go-redis/redis#ClusterClient

**Comment by iegomez** [comment]
Hello there, @rechandler12 ! I know I've been neglecting this issue for some days, either for lack of time or, more recently, because I've been taking care of longer dated or lower hanging ones these last couple of days. I believe it shouldn't be too hard to tackle so I'll give it a try tomorrow after work, but if you have done any tests during these days please share your findings or even open a PR with a working solution. In any case, sorry again for the delay, too much stuff going on lately but I'll get to it as soon as possible.

**Comment by iegomez** [comment]
Hi again! I have an almost ready implementation, just need to figure out the best way of dealing with the different signatures for `Set` and `SAdd` for instance and cluster Redis clients since they differ but are important for testing purposes. I hope to have that solved tomorrow and then I'll open a PR for you to look.
Does that sound good, @rechandler12 ?

**Comment by rechandler12** [comment]
Hi! Sorry for the late response. I have also lack of time :(
I don't know GO, so I don't have any pull request. I haven't time to test it also :/

It sound great :) I'am waiting for PR.

**Comment by iegomez** [comment]
Here's a WIP PR: https://github.com/iegomez/mosquitto-go-auth/pull/71

I need to clean it up and test a couple of things before calling it done, but the bulk of the work is done.

**Comment by iegomez** [comment]
So I made some tests and there were some weird results with tests failing only on some runs, so I changed the Redis backend tests to just use assert and ditched goconvey and everything worked. 

I know testing has a lot of room for improvement and that's the next thing in my list, but for now at least it shows that a Redis cluster passes the same exact tests that a single instance configured backend does. I also realize your concern was cache and not the Redis backend specifically, but I based the former on the dual implementation I did for the latter so it should work. 

So yeah, I'm testing the backend instead of the cache functionality, but they use the same interface to abstract a single instance or cluster Redis client, so I expect that to work without problems. That said, I'm merging the PR but leaving the issue open until you can confirm that it indeed works without issues.

**Comment by rechandler12** [comment]
Sorry for a dalay but I have a lot of work. I'll check it out next weekend

**Comment by rechandler12** [comment]
I have 2 problems
1. Still doesn't work (or I cannot configure it properly). My config:
`    auth_plugin /mosquitto/go-auth.so
    auth_opt_backends mysql
    auth_opt_cache false
    auth_opt_cache_reset true
    auth_opt_cache_host mosquitto-auth-cache-redis-cluster.mqtt.svc.cluster.local
    auth_opt_cache_port 6379
    auth_opt_cache_password xxx
    auth_opt_cache_db 0
    auth_opt_cache_mode cluster
    auth_opt_cache_addresses 10.244.0.133:6379,10.244.0.151:6379,10.244.0.162:6379,10.244.0.174:6379,10.244.0.178:6379,10.244.0.200:6379
`

And I've got these errors:
`
time="2020-06-08T07:10:56Z" level=error msg="set auth cache: MOVED 10621 10.244.0.162:6379"
`
2. I think this option: `auth_opt_cache_addresses` isn't very good idea in k8s cluster because these servers addressees can change dynamically. In k8s I use only service address in my example it's: `mosquitto-auth-cache-redis-cluster.mqtt.svc.cluster.local`

**Comment by iegomez** [comment]
1. Yeah, I'm checking the [Cluster spec](https://redis.io/topics/cluster-spec) and `MOVED errors` should be handled by the client by either keeping track of the nodes or resetting the layout on errors. So I'll have to take a look again to see if that's supported by the package in use.

2. I think this can't or shouldn't be handled by a client though: if your Cluster in K8s keeps changing IPs for your nodes, then you shouldn't expose IPs but hostnames instead if you expect it to be publicly accessed. On the other hand, if everything lives inside the same K8s cluster, you should then be able to just use service names as hostnames and the correct ports for them.

Now, I don't know how you're setting either your K8s cluster nor your particular Redis cluster (and I'm no expert in either), so helping with how to configure this correctly is a bit difficult. But I would say that if you get any dummy service inside your K8s cluster to access the Redis one through service/host names and ports, then the plugin should be able too.

In any case, there may be simpler approaches to this. Granted, I don't know your requirements so this may not suit you (maybe you do need cache replication or something), but anyway:

- Can't you just have a Redis instance in the same image where `mosquitto` lives that's only locally accessed and serves only for cache?
- Alternatively, you could have a standalone (no cluster) Redis service managed in the K8s cluster that, again, serves only as cache and isn't accessible outside the cluster.

**Comment by rechandler12** [comment]
1. Thanks
2. Alright, I handle it :)
I have to think about solutions and choose one but I know what I have to do.

Thanks for your help.

**Comment by iegomez** [comment]
Hey, @rechandler12!

I did some digging and supposedly the Redis package in use should handle `MOVED` errors by retrying (8 times by default), but since that is not working I'm implementing a strategy that reloads the cluster state on `MOVED` error and does a single retry after it. Here's an example implementation for the backend's `GetUser` method, but it would look fairly similar for Cache:
```
//GetUser checks that the username exists and the given password hashes to the same password.
func (o Redis) GetUser(username, password, _ string) bool {

	ok, err := o.getUser(username, password)

	if err == nil {
		return ok
	}

	//If using Redis Cluster, reload state and attempt once more.
	if isMovedError(err) {
		err = o.conn.ReloadState(o.ctx)

		// This should not happen, ever!
		if err == singleClientError {
			return false
		}

		//Retry once.
		ok, err = o.getUser(username, password)
	}

	if err != nil {
		log.Debugf("redis get user error: %s", err)
	}
	return ok
}

//getUser checks that the username exists and the given password hashes to the same password.
func (o Redis) getUser(username, password string) (bool, error) {

	pwHash, err := o.conn.Get(o.ctx, username).Result()

	if err != nil {
		return false, err
	}

	if common.HashCompare(password, pwHash, o.SaltEncoding) {
		return true, nil
	}

	return false, nil
}
```

I'm still polishing it, but hopefully I'll have a feature branch for you to test against soon. That said, it immediately smells like a poor strategy: if caching needs reloading, then you might be better off asking the backend directly instead of using a cache! But since it would be useful for the Redis backend itself when using a cluster, I thought why not implement it anyway and add it to the plugin's cache: maybe moving is not that common and you can take the reloading hit every now and then while still having a fairly decent cache most of the time.

Related to this, I'm thinking in adding an in memory local cache as an option to simplify caching. There may already be some Go package that provides good support, but if not I'm thinking in adding something really, really simple though: plain maps with limited size, basic eviction policies and no cache expiration. Again, that doesn't sound too good, but it's just one more tool that someone may find useful. This would go in a different branch/PR so we can get Cluster working correctly first.

I'll keep you updated!

**Comment by iegomez** [comment]
Here's a PR for handling `MOVED` errors: https://github.com/iegomez/mosquitto-go-auth/pull/80

I don't have the infrastructure in place to test this against a k8s Redis cluster and little time to build it up, so it'd be super useful if you can try out that feature branch and let me know how it works. 

I ran the test suite and am pretty sure it wouldn't break anything since it's only checking for a specific error and retrying, but still I'm hesitant to merge to master before it is tried. If you think you'd benefit from having this released as a Docker image, let me know and we'll see what we can come up with; worst case, we'll just merge it so the image gets built automatically fro master, quickly check and revert if anything goes wrong.

**Comment by iegomez** [comment]
I couldn't resist it: a new local cache is available using [go-cache](https://github.com/patrickmn/go-cache) and there's a new cache package to clean the implementation. This is part of the same branch and PR, so go nuts trying that cache too if you want.

**Comment by iegomez** [comment]
@rechandler12 I just added tests and thus will merge the PR. Let me know how it works when you get a chance to try it.

**Comment by iegomez** [comment]
Hey, any news on this?

**Comment by rechandler12** [comment]
Hi!
I'm gonna check this tomorrow and I let you know.

**Comment by rechandler12** [comment]
Hi!
I tested redis cache and get this error:

```
time="2020-07-05T20:02:20Z" level=info msg="redisCache activated"
time="2020-07-05T20:02:20Z" level=info msg="started redis cache"
time="2020-07-05T20:02:20Z" level=info msg="flushed redis cache"
1593979340: Opening ipv4 listen socket on port 1883.
1593979340: Opening ipv6 listen socket on port 1883.
1593979340: New connection from 127.0.0.1 on port 1883.
time="2020-07-05T20:02:20Z" level=error msg="set auth cache: unsupported reload state operation for Redis single client"
```
It could be also problem with my configuration. So If you have any idea what you can do with it or what I should check, just let me know.

I also tested local cache and it work perfectly. It solves all my issues. So thank you very much :) Great job <3

**Comment by iegomez** [comment]
Sorry for yet another late response, this week's sprint at work was a killer one!

> time="2020-07-05T20:02:20Z" level=error msg="set auth cache: unsupported reload state operation for Redis single client"
 
That's odd since that error would come up when using a **single instance client** and seeing `MOVED` error, which makes no sense, I just added it to meet the interface. So either I royally screwed up the implementation or something really weird is going on. I'll give that a check.

Happy to hear local cache works perfectly though!

**Comment by iegomez** [comment]
@re

> It could be also problem with my configuration. So If you have any idea what you can do with it or what I should check, just let me know.

@rechandler12 Could you share your configuration to see if I can spot any issues?

**Comment by rechandler12** [comment]
@iegomez I'm on holiday. I'll be back on Sunday.

**Comment by rechandler12** [comment]
My config:

    listener 1883
    allow_anonymous false
    
    auth_plugin /mosquitto/go-auth.so
    auth_opt_backends mysql
    auth_opt_cache true
    auth_opt_cache_type redis
    auth_opt_cache_mode cluster
    auth_opt_cache_host mosquitto-auth-cache-redis-cluster.mqtt.svc.cluster.local
    auth_opt_cache_addresses 10.244.0.122:6379,10.244.0.160:6379,10.244.0.188:6379,10.244.0.43:6379,10.244.0.64:6379,10.244.0.89:6379
    auth_opt_cache_port 6379
    auth_opt_cache_password xxx
    auth_opt_cache_db 0
    auth_opt_cache_reset true
    auth_opt_mysql_allow_native_passwords true
    auth_opt_mysql_host mariadb.mqtt.svc.cluster.local
    auth_opt_mysql_port 3306
    auth_opt_mysql_user mosquitto
    auth_opt_mysql_password xxx
    auth_opt_mysql_dbname mosquitto_auth
    auth_opt_mysql_userquery SELECT password FROM user WHERE username = ? limit 1
    auth_opt_mysql_superquery SELECT COUNT(*) FROM user WHERE username = ? AND super = 1
    auth_opt_mysql_aclquery SELECT topic FROM acl WHERE uid = (SELECT id FROM user WHERE username = ? limit 1) AND (rw = ? or rw = 3)

**Comment by iegomez** [comment]
@rechandler12 I'm so sorry I never realized you posted your config, I turned off notifications without explicit mentions some months ago since I use my this same account for work and I was getting too much irrelevant notifications from little changes on work repos, so I never got an email. :facepalm: 
As I've mentioned in other issues and PRs, the past couple of weeks have been very time consuming, but now I know you shared some details I'll try to check it as soon as I get some time. Of course, let me know if you already fixed it and thus is no longer relevant.

Again, sorry and cheers!

**Comment by iegomez** [comment]
@rechandler12 Should I look at this or is it already resolved?

**Comment by rechandler12** [comment]
I apologize I didn’t respond earlier. I’ve been busy and missed notification. 

I think you should close this issue. I use local cache, gave up on redis and everything is working good.

**Comment by iegomez** [comment]
Ok, thanks for replying, i'll close it for now and revisit it later if needed.
