### ISSUE TITLE
Postgres ACL query error 'got 2 parameters but the statement requires 1'

### ISSUE THREAD

**Issue by garethhcoleman** [iegomez/mosquitto-go-auth#75]
Hi! Great plugin many thanks!!

I have used it successfully with files backend, and now with both postgres and JWT. However, one part is causing me problems, almost certainly my mis-configuration, but having struggled with it for hours I now appeal to you and the hive mind!

My auth query is pretty vanilla in that it seems similar to the example given..

`auth_opt_pg_aclquery SELECT "partNumber" || '/#' FROM "chamber" WHERE "chamberId" = $1 LIMIT 1`

However, I get this strange (to me) error message:
`level=debug msg="PG check acl error: pq: got 2 parameters but the statement requires 1`

When I run the query in pgadmin I see a single result, I can't work out what the second parameter is!

I looked through the source code and as a newcomer to go I discovered:

a) it's a nice looking language, very modern
b) I couldn't find the cause of my issue

I liked it so much I spent several happy hours implementing an argon2 password hashing and verification mechanism to replace the PBKDF2 one in common/utils.go. Happy to share the code if useful - currently I lack the knowledge to integrate it properly into your system with a configuration item etc. and make a pull request.

So I hope that's enough context - happy to supply mosquitto conf files etc if it helps, I'm using mosquitto 1.6.10 and the latest commit of this plugin against Postgres 12.3/Debian 9.

Thanks you so much in advance if you are able to spare a minute to consider my issue, I really appreciate it.

**Comment by iegomez** [comment]
Hi and thanks for the kind words and interest on this project.

1. Regarding your issue, I just noticed the example configuration for Postgres was truncated, I just fixed that. Now it show this:
```
auth_opt_aclquery select distinct 'application/' || a.id || '/#' from "user" u inner join organization_user ou on ou.user_id = u.id inner join organization o on o.id = ou.organization_id inner join application a on a.organization_id = o.id where u.username = $1 and $2 = $2
```
As you may see in the ACL checking method, the Postgres backend passes both `username` and `acc`:
```
err := o.DB.Select(&acls, o.AclQuery, username, acc)
```
Now, since you don't care about `acc` and don't mention the second param in the query but it's being passed anyway, Postgres will complain about getting 2 parameters when the query just mentioned 1. You may bypass it by just adding something like `and $2 = $2` to the query, just as was supposed to be shown in the truncated example.

2. Contributions are very welcome! I don't want to replace PBKDF2 entirely since it's used for [ChirpStack auth](https://www.chirpstack.io/guides/mqtt-authentication/), but adding more methods would be nice. This would involve adding options to select which method to use, which could be global or backend wise. In any case, you could open PR that adds support for Argon2 alongside PBKDF2 and we can work from there to integrate it and make it a usable option.

**Comment by garethhcoleman** [comment]
1. Of course!! <slap forehead>

I was staring at that DB.Select and didn't see it - I think I was convinced it was an error on the plugin side not the postgres side. Oh what a relief!

Thank you so much for responding so quickly - I've just made the change you suggested and all is gravy.

2. I'll get on and test my contribution - yes of course I didn't think the plugin would be enhanced by a breaking change!! I imagined there could be an additional non-mandatory configuration for 'auth_opt_hash_alg' that would default to 'pbkdf2' but could be set to 'argon2id'.

Should I fork your project and then work on it (with a little bit of your help please) to get my contribution into shape?

Cheers!!

Gareth

**Comment by iegomez** [comment]
> Should I fork your project and then work on it (with a little bit of your help please) to get my contribution into shape?

That sounds good! We could take the time to add `bcrypt` too, which is something I've been meaning too, but let's see how it goes.

Cheers!

**Comment by garethhcoleman** [comment]
Ok thank you again and I look forward to working with and learning from you.

Kind regards

Gareth
