### ISSUE TITLE
Automatic build for official docker image on dockerhub

### ISSUE THREAD

**Issue by LolHens** [iegomez/mosquitto-go-auth#76]
Hi there! I was wondering why the image on dockerhub (https://hub.docker.com/r/iegomez/mosquitto-go-auth) was so outdated.
Nowadays it is pretty easy to just set up an automated build for repositories and since the Dockerfile is already there it would only take a few clicks to set it up.
For now I just created my own docker image but it would be pretty cool to see an automatically updated official one.
I just created the image on dockerhub, selected the right repository and selected the Dockerfile in the root directory of the repository and added the master branch to the automated build and that's it.
![image](https://user-images.githubusercontent.com/1524059/84939415-965b1000-b0de-11ea-8622-bca880c6db0c.png)

Or is there another reason why this is not automated?

**Comment by iegomez** [comment]
Hey, @LolHens, thanks for bringing this up. There's no special reason, just forgot about it when I added basic Docker support. Most of the later changes have been contributions by others, so I never realized about that. I actually need to go over the two different Dockerfiles, but in this case I think we'd want to use `docker/Dockerfile` for Dockerhub `master` auto build since that's the new that pulls latest master, while the other one needs some tweaking to get the plugin version from the release and build that version. Right?

For now I'm adding `master` auto build as `latest` image, but would be very grateful if you wanna help setting up something better.

**Comment by LolHens** [comment]
I've compared the two files and they are nearly identical except that one pulls the files from github. I think for the overall workflow it would be much easier to use the one from the repository root which doesn't pull from github because then you can build older versions, other branches or pull requests. One difference I found was that this one doesn't copy the pw utility to the final image.
If you use the Dockerfile in the repository root you would just need to set up the two build rules like in the screenshot above and docker will build on each change of the master branch and push it to the latest tag and it will also automatically build and push a tag for every release.

**Comment by iegomez** [comment]
That's very helpful!

I just changed the rule to match yours, so in a few minutes builds should be available.

**Comment by LolHens** [comment]
Thank you very much!

**Comment by iegomez** [comment]
I never really found the time to master or at least get better at docker, so I still struggle with some things from time to time. So thank you for your contributions!

**Comment by LolHens** [comment]
BTW: you can even let docker build past releases by manually adding their tag like this:
![image](https://user-images.githubusercontent.com/1524059/84951896-6701ce80-b0f1-11ea-9f8d-cdcbc551ab12.png)
