### ISSUE TITLE
Doc for jwt_superuser_uri, jwt_aclcheck_uri

### ISSUE THREAD

**Issue by yanosz** [iegomez/mosquitto-go-auth#92]
Nice project! I'm having fun using JWT but I'm a little bit confused regarding `jwt_aclcheck_uri` and `jwt_aclcheck_uri`. What is a HTTP-server supposed to do when called? I'm unable to spot some docs explaining the reqest and response payloads - or it's just me being confused.

I'd cool, if you could give some insights.
Thx, yanosz

**Comment by iegomez** [comment]
Hey, @yanosz! Docs are at https://github.com/iegomez/mosquitto-go-auth#jwt, but I'll give you some examples on how this works.

Same as with `http` backend, the endpoint for `user`, `superuser` and `acl` needs to respond depending on the option you passed for JWT backend. So for example let's say you configured the plugin with these (and other relevant) options:
```
jwt_host example.org
jwt_port 3000
jwt_getuser_uri /user
jwt_superuser_uri /superuser
jwt_aclcheck_uri /acl

jwt_response_mode status
jwt_params_mode json

jwt_with_tls true
jwt_verify_peer true
```
So let's start with `user` check. With these settings whenever the plugin receives an authentication check from mosquitto - which passes `username`, `password` and `clientid`-,  it'll do a request to the given server to ask if the user passes auth. Since this is JWT, it assumes the `username` it got from mosquitto corresponds to the JWT token and ignores both `password` and `clientid`. So the request would look something like:
```
POST https://example.org:3000/user
Content-Type: application/json
Authorization: Bearer username

{}
```
Since the selected option for response is `status`, then the plugin will interpret any `2xx` status code as auth granted, and any other other code as not granted. If the expected response was plain text, then the server should respond with a simple "ok" body for auth granted, while anything else (ideally an error message) will mean not granted; when set to json, `{Ok: true, Error: ""}` is the auth granted expected response, while `{Ok: false, Error: "Some error message"}` is for not granted. Notice that in both text and json cases, if the status code is other than `2xx`, that's interpreted as not granted too.

The `superuser` request works basically the same but with a different endpoint (in this case `https://example.org:3000/superuser`), and the server should answer if the user corresponding to the given token is a superuser or not.

The ACL check endpoint is a bit more interesting because besides sending the authorization header for the server to check the token, it sends data about the ACL check. So when the plugin gets an `ACL` check from mosquitto, it'll do a request to the `aclcheck` endpoint with the same old `Authorization` header, but now also with a json body or regular http form data depending on the params mode, so for json it would look something like this:
```
POST https://example.org:3000/acl
Content-Type: application/json
Authorization: Bearer username

{
  "topic": "some/topic",
  "clientid": "some-client-id",
  "acc": 1
}
``` 
When using form data instead of json, headers will have `Content-Type` set to `application/x-www-form-urlencoded` as well as include a `Content-Length` one. As with the previous checks, the server needs to respond if the given user identified by the JWT token is granted access to `some/topic` with `acc` permissions (read, write or subscribe).

I hope that clears out how the JWT backend works, but let me know if you have any more doubts.

Cheers!

**Comment by yanosz** [comment]
Thanks for your help! That's clarifies a lot!

Is it ok, if a file a PR for the docs?

**Comment by iegomez** [comment]
Sure! I thought the docs were clear, but I'm of course biased and they seem no to be, so that'd be helpful.

Thanks!

**Comment by iegomez** [comment]
Hey, @yanosz, thanks again for your interest in contributing. I understand if you couldn't find the time to do it and thus will close the issue for the time being. Feel free to reopen it for any discussion, or just file a PR with the changes if you get any time.

Cheers!
